name: com.powerkidsx
description: Anaokulu ve Kresler icin mobil uygulamadir.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 67.0.0+67

environment:
#  sdk: ">=2.17.6 <3.0.0"
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5 #state yönetimi
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.4
  group_button: ^5.0.1
  persistent_bottom_nav_bar_v2: ^4.2.5 #nav bar
  intl: ^0.18.0 #takvim dili
  permission_handler: ^10.2.0
  image_picker: ^0.8.6 #imaj seçme
  file_picker: ^5.2.2 #seçilen imajların gösterimi için
  dropdown_button2: ^1.8.9
  loader_overlay: ^2.1.0
  url_launcher: ^6.1.6
  cached_network_image: ^3.2.1


  flutter_sound: ^9.2.13 #oynatma
  audio_session: ^0.1.16

  appinio_video_player: ^1.2.1 #video izleme,controller

  carousel_slider: ^4.1.1 #fotoğraf albüm
  extended_image: ^8.0.2 #resim zoom in out
  image_gallery_saver: ^1.7.1 #galeri resim kaydetme
  dio: ^4.0.4 #image indirmek için
  path_provider: ^2.0.15
  path: ^1.8.2

  flutter_chat_ui: ^1.6.0
  audio_waveforms: ^0.1.4
  get_time_ago: ^1.1.8

#  calendar_agenda: ^0.0.2+3
  scrollable_positioned_list: ^0.3.7


  location: ^4.4.0 #konum bilgisi alma
  latlong2: ^0.8.1 #konum arası mesafe hesaplama

#  bildirim
  http: ^0.13.5
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.6.4
  firebase_core: ^2.14.0

  flutter_native_splash: ^2.3.1 #dart run flutter_native_splash:create

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/image/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
